# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - HoodedUnicorn
  categories:
    - title: Breaking News 🛠
      labels:
        - Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Minor
        - Patch
